server:
  port: 10002
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 10000
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093
